### ISSUE TITLE
Clear bookmarks

### ISSUE THREAD

**Issue by Milliw** [robcaa/numbered-bookmarks#1]
Hi!
How to clear all bookmarks at once?

**Comment by robcaa** [comment]
Hi!
Maybe the CTRL+SHIFT+0 hotkey is a good choice for this feature. Or what do you think?

**Comment by robcaa** [comment]
OK 
I wrote the necessary function, but the CTRL+SHIFT+0 hotkey is not work so I set the  hotkey to CTRL+SHIFT+DELETE

In addition, some errors fixed.
You can download the new extension ;)

**Comment by Milliw** [comment]
That was fast! :D

**Comment by robcaa** [comment]
Because I need this plugin, and the idea to delete all bookmarks is good. :)
