### ISSUE TITLE
OSX?

### ISSUE THREAD

**Issue by CardcaptorStacey** [robcaa/numbered-bookmarks#2]
Can't seem to create any bookmarks on Mac!

**Comment by robcaa** [comment]
I don't have Mac .So I could not test. But it should work.

The [keybinding API](http://brackets.io/docs/current/modules/command/KeyBindingManager.html#-addBinding) says:
"NOTE: If platform is not specified, Ctrl will be replaced by Cmd for "mac" platform"

You try CMD+SHIFT+number and nothing?
Maybe the bookmarks work, just not shown the number.

If it does not work absolutely. Can you see the brackets console (F12) and place a bookmark and watch in console if any error shown.

**Comment by CardcaptorStacey** [comment]
Thanks for getting back to me

Only CMD+SHIFT+2 seems to work. I think they other buttons are used for system and Brackets. Looks like CMD+SHIFT+1 is used as a shortcut to expand all in the Bracket view menu...

**Comment by robcaa** [comment]
What do you think. Which combination of keys would be good for Mac?
If you help me I add that shortcuts to the extension.

**Comment by CardcaptorStacey** [comment]
CMD+ALT+#?

**Comment by robcaa** [comment]
Ok. When I have a little time, I will make this hotkeys for MAC and you can test it.

**Comment by robcaa** [comment]
OK. I added MAC hotkeys:
- Cmd-ALT-Delete      delete all bookmarks
- Cmd-ALT-#           place bookmark
- Cmd-#               jump to bookmark

Can you test these hotkeys? Just replace main.js and restart brackets.

**Comment by CardcaptorStacey** [comment]
Damn, doesn't seem to work :( Could we try a different combination?

CMD-SHIFT-Delete - delete all bookmarks
CMD-SHIFT-# - place bookmark
CMD-ALT-# - jump to bookmark

Also CMD-1 (to jump to bookmark 1 is already used by Brackets to "Collapse All")

**Comment by CardcaptorStacey** [comment]
Damn, doesn't seem to work :(

CMD-1 (to jump to bookmark 1 is already used by Brackets to "Collapse All") - so maybe a new combination?

edit: Wait... think I messed up!!!

**Comment by CardcaptorStacey** [comment]
I'm a silly sausage. It does work great now, thank you! Is there 1-9 of bookmarks?

Still can't skip to bookmark 1 as it is already used. Can the jump combination we changed? CMD+SHIFT+ALT+#? CMD+SHIFT+1 is already used by brackets

**Comment by robcaa** [comment]
Sorry for the late reply.
CMD+SHIFT+ALT+# is not too complicated?

If you really think that this is a good choice, I'm going to set it.
