### ISSUE TITLE
Keyboard shortcut conflict

### ISSUE THREAD

**Issue by cipo28** [robcaa/numbered-bookmarks#3]
The new 1.6 Brackets version has introduced the no-distraction view with `ctrl+shift+2`: now it's impossible to set the 2nd line bookmark. Can I suggest to implement a shortcut with `ctr+ALT+x`?

**Comment by robcaa** [comment]
In addition, the MAC does not work on the current combination (https://github.com/robcaa/numbered-bookmarks/issues/2).
It seems that must to change the keyboard shortcuts, but I have a little trouble.

The proposed combination will be conflict by the Hungarian keyboard layout.
In the picture you can see: 
![hungarian layout](http://cdn.fontmeme.com/images/hungarian-keyboard-550x183.png)
There are many special characters, the Hungarian keyboard can be reached with this combination.

It should be a combination that is good for everyone.
What do you think about this combination:
CMD + SHIFT + ALT + #

Or maybe we need a configuration option?
Discuss this and I will make the changes.

**Comment by cipo28** [comment]
I was thinking about the "insert" key, but it will change everytime the writing mode... so I think yours is the most generic applicable.
I've also noticed that the bookmarks were lost when saving the file, do I need to open another issue?

**Comment by robcaa** [comment]
OK I will make the necessary changes, as it becomes a little time. (maybe tomorrow)

Yes open a new issue, and please describe (detailed) how to reproducate the bug.
I can not reproducate the bug, but I don't installed the new version yet.
